# -*- coding: utf-8 -*-
"""EBill.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G4llrdOo8q1AJLq9IRQLMUXU2X_EBkKG
"""

import pandas as pd
import numpy as np

df = pd.read_csv('download (8).csv')
df

df = df[['timestamp','AC']]
df.head()

df[['Date','Time']] = df.timestamp.str.split(" ",expand=True,)
df.head()

df = df.drop("timestamp",axis = 1)
df.head()

df.head()

df[['Year','Month','Date']] = df.Date.str.split("-",expand=True)
df.head()

df[['Time','None']] = df.Time.str.split("-",expand=True,)
df.head()

df = df.drop("None",axis = 1)
df.head()

df = df[['Year','Month','Date','Time','AC']]
df.head()

july = df.loc[df['Month'] == '07']
july

August = df.loc[df['Month'] == '08']
August.head()

df.groupby('Date')['AC'].sum()['01']

dict = {'Date':['01','02','03','04','05'],
        'Consumption':[df.groupby('Date')['AC'].sum()['01']/1000,df.groupby('Date')['AC'].sum()['02']/1000,df.groupby('Date')['AC'].sum()['03']/1000,df.groupby('Date')['AC'].sum()['04']/1000,df.groupby('Date')['AC'].sum()['05']/1000]}
aug = pd.DataFrame(dict)
aug

aug.to_csv('discrete.csv')


augc = aug.copy()

augc['total'] = augc['Consumption'].cumsum()
augc = augc.drop('Consumption',axis=1)
augc.head()

augc.to_csv('cont.csv')


